# -- Data --
dataset = "amass-p1"
yolo_model = "yolov8n-pose"
mode = "triang"
as_testset = "cmu" # only used when PROTOCOL = 2
skinned_mesh_topology = "smpl"
cache_dir = ".cache"

# -- Training --
batch_size = 128
win_len = 40
win_overlap = 5
zero_betas = false
max_epoch = 2
epochs_per_save = 1
save_dir = "./temp"

# -- Kalman --
with_kalman_filter = true
filter_name = "ConstantAcc"

# -- Model --
model_config = "anim/model_configs/hmd-poser-ext-head-centered.toml"

# -- System --
device_str = "cuda"
dtype_str = "float32"
dataloader_num_workers = 0
